# Generated by Django 6.0.1 on 2026-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
