# Generated by Django 6.0.1 on 2026-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bookmark_options_alter_blogpost_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('link', 'Link'), ('note', 'Note'), ('code', 'Code')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('url', models.URLField(blank=True, help_text='URL for link-type items')),
                ('body', models.TextField(help_text='Markdown content')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='feed_items', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Feed Item',
                'verbose_name_plural': 'Feed Items',
                'ordering': ['-created_date'],
            },
        ),
    ]
