# Generated by Django 6.0.1 on 2026-03-09 02:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_feeditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("github", "GitHub"), ("gumroad", "Gumroad")],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("release", "Release"), ("product", "Product")],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("owner", models.CharField(blank=True, max_length=100)),
                ("repo", models.CharField(blank=True, max_length=200)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("price", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("product_slug", models.CharField(blank=True, max_length=200)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "mirrored_feed_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_update",
                        to="blog.feeditem",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_source_external_id",
                    )
                ],
            },
        ),
    ]
